site:
  title: Demo Site
  url: https://stepanovserg.github.io
  start_page: component-a::sidebar.adoc
content:
  sources:
  - url: https://github.com/stepanovserg/demo-docs-component-a.git
    branches: [main]
  #  start_path:  
asciidoc:
  attributes:
    experimental: ''
    idprefix: ''
    idseparator: '-'
    page-pagination: ''
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
